### ISSUE TITLE
WebForm sample not generating signature

### ISSUE THREAD

**Issue by mvdzwaan** [andyfmiller/LtiSamples#2]
I've tried to use your Webform launch.ashx sample which ends with

context.Response.WriteLtiRequest(ltiRequest, "secret")

But the imsglobal simple provider says :

Could not establish context: Invalid signature ours= TpVZ7AJ1SrJDtIynxAYpIjVlNqI= yours=

I can see all POST parameters are available.

Using NuGet LtiLibrary 1.4.2 and based on the sample site (also using NuGet)

**Comment by mvdzwaan** [comment]
Just checked with fiddler, but the oauth_signature hidden field is generated (with the correct signature) but the IMSGlobal site still says I did not provide a signature

**Comment by mvdzwaan** [comment]
Noticed the problem. The generated form has 

<input type='hidden' name='oauth_signature' value='iwZPqI7zQQkdiKwThNuJQKTIhPo='

so it's missing a />

**Comment by mvdzwaan** [comment]
I did another 'Install-Package LtiLibrary' and got the 1.4.5 this time, in which this bug was fixed.

The Install-Package LtiLibrary.Sample had installed the 1.4.2 with the bug

**Comment by andyfmiller** [comment]
Thank you for taking the time to document both the problem and the solution.

I have mixed feelings about the sample package in NuGet. It is hard for me to keep it up to date.
