### ISSUE TITLE
integration with BigBlueButton

### ISSUE THREAD

**Issue by lylia** [andyfmiller/LtiSamples#3]
could you give me more details to integrate with virtual classroom of bigbluebutton please:  the consumer send the request to BBB provider but the response is " connection couldn't be established" , i 've checked that the Secret and URL are correct....any suggestion ?

**Comment by lylia** [comment]
![image](https://cloud.githubusercontent.com/assets/9728533/8205143/364e5d5c-14ee-11e5-959d-674ffbf2a7a0.png)

**Comment by andyfmiller** [comment]
I'm sorry, but I don't have any suggestions.
