### ISSUE TITLE
Can't Run Solution

### ISSUE THREAD

**Issue by sktzoootech** [andyfmiller/LtiSamples#6]
Hi,

Im new to .NET and would like some help in setting up this sample.  Can you give me some steps on how I can set this up properly on my local machine.

Kind Regards,

Davis

**Comment by KennyKaplanHP** [comment]
It looks like the original set of projects included some OWIN extensions and ASP.Net security handlers that didn't make their way into the new solutions. Is there a chance that those will get migrated into the core project as well?

**Comment by Korporal** [comment]
Likewise - the solution refers to LtiLibrary projects with "Owin" in their name. These two project are neither in this repo or the related LtiLibrary repo...

**Comment by andyfmiller** [comment]
Hello All,

The LtiSamples solution file references the projects in https://github.com/andyfmiller/LtiLibrary. You need both LtiSamples and LtiLibrary for the solution to work. Or you can use NuGet to get LtiLibrary and then replace all the project references with references to the compiled libraries. I think the first option is probably easier.

![solutionexplorer](https://cloud.githubusercontent.com/assets/2666882/13590657/90dcc11e-e496-11e5-86d2-5ad626648b19.png)

Once the solution compiles, you can run the SimpleLti project which is both a Tool Consumer and Tool Provider. Then try running both Consumer and Provider (two separate projects/web sites).

**Comment by andyfmiller** [comment]
I added a Getting Started section to the [readme](https://github.com/andyfmiller/LtiSamples).
