### ISSUE TITLE
Embedded tool interface

### ISSUE THREAD

**Issue by The-Futurist** [andyfmiller/LtiSamples#7]
I'm wondering if any of the samples show a working example of a consumer web-app that uses an iframe to expose an LTI tool? I'm very new to LTI and somewhat out of date with ASP.NET (but otherwise have a decade of .Net).

Any info/help much appreciated!

**Comment by andyfmiller** [comment]
I'm afraid not, but it is very easy. For example, the home page of
LtiSamples/SimpleLti has a Launch link that loads Views/Consumer/Launch. If
you want the tool to load within an iframe, change the Launch link to load
a page (e.g. Index) with an iframe that loads Launch.

**Comment by The-Futurist** [comment]
Thanks Andy. I'm moving along OK just a bit new to MVC. I'm crafting a general purpose LTI tool server using your library and its going well. The iframe thing is a curiosity really.

Date: Sat, 12 Mar 2016 09:50:45 -0800

**Comment by andyfmiller** [comment]
Loading an LTI tool into an iframe becomes problematic if the container page is loaded with https, but the tool is loaded with http. The browser will either refuse to load the tool or complain with a scary looking message. If you control both the consumer and provider, then you can completely avoid this problem. If you are the provider and always load over https, then it will not be a problem either. But if you are the consumer and cannot control the provider (i.e. users enter the LTI launch information), then it would be a good idea to warn the user about the problem and maybe stear them toward loading the tool in a new window/tab.
